Introduccion a estructura de datos

Introduccion a las series

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
ventas = pd.Series([22,15,70])
ventas

0    22
1    15
2    70
dtype: int64

In [ ]:
ventas = pd.Series([22,15,70], index=['Enero','Febrero','Marzo'])
ventas

Enero      22
Febrero    15
Marzo      70
dtype: int64

In [ ]:
ventas[0]

<ipython-input-5-eacc5df2ea8a>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ventas[0]

22

In [ ]:
ventas['Enero']

22

In [ ]:
#Para conocer el tipo de datos dentro de las series
ventas.dtype

dtype('int64')

In [ ]:
#Para conocer el nombre de los indices
ventas.index

Index(['Enero', 'Febrero', 'Marzo'], dtype='object')

In [ ]:
#Cambiar el nombre a la feature o caracteristica
ventas.name = 'Ventas 2024'
ventas

Enero      22
Febrero    15
Marzo      70
Name: Ventas 2024, dtype: int64

In [11]:
#Poner un titulo a los index
ventas.index.name = 'Meses'
ventas

Meses
Enero      22
Febrero    15
Marzo      70
Name: Ventas 2024, dtype: int64

In [12]:
ventas.shape

(3,)

###Creando series desde diccionario

In [26]:
d={"Enero":7,"Febrero":9,"Marzo":3}
type(d)

dict

In [27]:
s=pd.Series(d)
s

Enero      7
Febrero    9
Marzo      3
dtype: int64

In [29]:
s.name = "valores"
s

Enero      7
Febrero    9
Marzo      3
Name: valores, dtype: int64

In [30]:
alex=pd.Series(d,index=['Enero','Febrero','Marzo','Abril'])
alex

Enero      7.0
Febrero    9.0
Marzo      3.0
Abril      NaN
dtype: float64

Introduccion a los datagramas

In [16]:
medidas=pd.DataFrame(
    {"Humedad":[41,20,30,80],
    "Salinidad":[22,15,30,80],
    "Maquinaria":["Si","No","No","No"],
    "Acidez":["Alta","Media","Baja","Baja"],
    "ph":[3,5,9,12]},
    index = ["La ureña","La pedregoza","Maria Bonita","Peru"]
)
medidas

              Humedad  Salinidad Maquinaria Acidez  ph
La ureña           41         22         Si   Alta   3
La pedregoza       20         15         No  Media   5
Maria Bonita       30         30         No   Baja   9
Peru               80         80         No   Alta  12

In [17]:
medidas.index.name = 'Fincas'
medidas

              Humedad  Salinidad Maquinaria Acidez  ph
Fincas
La ureña           41         22         Si   Alta   3
La pedregoza       20         15         No  Media   5
Maria Bonita       30         30         No   Baja   9
Peru               80         80         No   Alta  12

In [19]:
print(medidas.dtypes)

Humedad        int64
Salinidad      int64
Maquinaria    object
Acidez        object
ph             int64
dtype: object

In [22]:
medidas.loc["Maria Bonita", "Humedad"]

30

In [23]:
medidas.axes

[Index(['La ureña', 'La pedregoza', 'Maria Bonita', 'Peru'], dtype='object', name='Fincas'),
 Index(['Humedad', 'Salinidad', 'Maquinaria', 'Acidez', 'ph'], dtype='object')]

In [24]:
#Conociendo los valores del dataframe
medidas.values

array([[41, 22, 'Si', 'Alta', 3],
       [20, 15, 'No', 'Media', 5],
       [30, 30, 'No', 'Baja', 9],
       [80, 80, 'No', 'Alta', 12]], dtype=object)

In [25]:
medidas.shape

(4, 5)

###Creacion de dataframe por medio de diccionarios

In [35]:
elementos={
    "Numero atomico":[1,6,47,88],
    "Masa atomica":[1,12,107,226],
    "Familia":["No metal","No metal","Metal","Metal"]
}
elementos

{'Numero atomico': [1, 6, 47, 88],
 'Masa atomica': [1, 12, 107, 226],
 'Familia': ['No metal', 'No metal', 'Metal', 'Metal']}

In [36]:
tabla_periodica=pd.DataFrame(elementos)
tabla_periodica

   Numero atomico  Masa atomica   Familia
0               1             1  No metal
1               6            12  No metal
2              47           107     Metal
3              88           226     Metal

In [37]:
tabla_periodica=pd.DataFrame(elementos,
                             index=["Hidrogeno","Carbon","Plata","Radio"],
                             columns=["Familia","Numero atomico", "Masa atomica"])
tabla_periodica

            Familia  Numero atomico  Masa atomica
Hidrogeno  No metal               1             1
Carbon     No metal               6            12
Plata         Metal              47           107
Radio         Metal              88           226

###Creando un dataframe a partir de un numpy

In [38]:
datos=np.array([[2,4,6,8],[4,6,7,4],[5,2,3,1]])
datos

array([[2, 4, 6, 8],
       [4, 6, 7, 4],
       [5, 2, 3, 1]])

In [39]:
unidades=pd.DataFrame(datos)
unidades

   0  1  2  3
0  2  4  6  8
1  4  6  7  4
2  5  2  3  1

In [41]:
unidades.index = ['La ureña', 'La pedregoza', 'Maria Bonita']
unidades.columns = [2021, 2022, 2023, 2024]
print(unidades)

              2021  2022  2023  2024
La ureña         2     4     6     8
La pedregoza     4     6     7     4
Maria Bonita     5     2     3     1

###Creacion de dataframes con diccionarios

In [49]:
medida_2020={"Ag":2,"Au":5,"Cu":3,"Pt":2}
medida_2021={"Ag":4,"Au":3,"Cu":6,"Pt":1}
medida_2022={"Ag":8,"Au":2,"Cu":15,"Pt":0}
unidades2=pd.DataFrame([medida_2020,medida_2021,medida_2022],
                       index=list(range(2020,2023)))
unidades2

      Ag  Au  Cu  Pt
2020   2   5   3   2
2021   4   3   6   1
2022   8   2  15   0

In [50]:
medida_2020={"Ag":2,"Au":5,"Cu":3,"Pt":2}
medida_2021={"Ag":4,"Au":3,"Cu":6,"Pt":1}
medida_2022={"Ag":8,"Pb":2,"Cu":15,"Pt":0}
unidades2=pd.DataFrame([medida_2020,medida_2021,medida_2022],
                       index=list(range(2020,2023)))
unidades2

      Ag   Au  Cu  Pt   Pb
2020   2  5.0   3   2  NaN
2021   4  3.0   6   1  NaN
2022   8  NaN  15   0  2.0

In [52]:
unidades2.head()

      Ag   Au  Cu  Pt   Pb
2020   2  5.0   3   2  NaN
2021   4  3.0   6   1  NaN
2022   8  NaN  15   0  2.0

###Trabajandoc con titanic.csv

Insepeccionando los dataframes

In [53]:
titanic=pd.read_csv("/content/titanic-train.csv")
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [54]:
#Revisar los primeros 5
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [55]:
#Revisar los ultimos 5
titanic.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [58]:
titanic.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
611,612,0,3,"Jardin, Mr. Jose Neto",male,NaN,0,0,SOTON/O.Q. 3101305,7.0500,NaN,S
41,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,1,0,11668,21.0000,NaN,S
287,288,0,3,"Naidenoff, Mr. Penko",male,22.0,0,0,349206,7.8958,NaN,S
491,492,0,3,"Windelov, Mr. Einar",male,21.0,0,0,SOTON/OQ 3101317,7.2500,NaN,S
234,235,0,2,"Leyson, Mr. Robert William Norman",male,24.0,0,0,C.A. 29566,10.5000,NaN,S

In [60]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [61]:
titanic.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [63]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Metodo value_counts devuelve una estructura conteniendo los valores presentes en la serie y el numero de ocurrencias de cada valor

In [65]:
s=pd.Series([3,1,2,1,1,4,1,2,np.nan])
s.value_counts()

1.0    4
2.0    2
3.0    1
4.0    1
Name: count, dtype: int64

In [67]:
titanic.value_counts()

PassengerId  Survived  Pclass  Name                                                  Sex     Age   SibSp  Parch  Ticket    Fare      Cabin  Embarked
2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)   female  38.0  1      0      PC 17599  71.2833   C85    C           1
572          1         1       Appleton, Mrs. Edward Dale (Charlotte Lamson)         female  53.0  2      0      11769     51.4792   C101   S           1
578          1         1       Silvey, Mrs. William Baird (Alice Munger)             female  39.0  1      0      13507     55.9000   E44    S           1
582          1         1       Thayer, Mrs. John Borland (Marian Longstreth Morris)  female  39.0  1      1      17421     110.8833  C68    C           1
584          0         1       Ross, Mr. John Hugo                                   male    36.0  0      0      13049     40.1250   A10    C           1
                                                                                                                                                       ..
328          1         2       Ball, Mrs. (Ada E Hall)                               female  36.0  0      0      28551     13.0000   D      S           1
330          1         1       Hippach, Miss. Jean Gertrude                          female  16.0  0      1      111361    57.9792   B18    C           1
332          0         1       Partner, Mr. Austen                                   male    45.5  0      0      113043    28.5000   C124   S           1
333          0         1       Graham, Mr. George Edward                             male    38.0  0      1      PC 17582  153.4625  C91    S           1
890          1         1       Behr, Mr. Karl Howell                                 male    26.0  0      0      111369    30.0000   C148   C           1
Name: count, Length: 183, dtype: int64